#!/usr/bin/env bash

python MIMIC_discretized_exp.py --mode train --identifier 1021-15mins-24hrs-joint-indep-measurement --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12
python MIMIC_discretized_exp.py --mode val --identifier 1021-15mins-24hrs-joint-indep-measurement --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12
python MIMIC_discretized_exp.py --mode test --identifier 1021-15mins-24hrs-joint-indep-measurement --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12


python MIMIC_discretized_exp.py --mode val --identifier 1020-15mins-24hrs-joint-random-order --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --include_before_death 24 --min_hours_of_patient 12 --batch_size 500
python MIMIC_discretized_exp.py --mode test --identifier 1020-15mins-24hrs-joint-random-order --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --include_before_death 24 --min_hours_of_patient 12 --batch_size 500
python MIMIC_discretized_exp.py --mode train --identifier 1020-15mins-24hrs-joint-random-order --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --include_before_death 24 --min_hours_of_patient 12 --batch_size 500

python MIMIC_discretized_exp.py --mode val --mgp_rnn_cls ManyToOneRNN --identifier 1023-15mins-24hrs-joint-indep-measurement-rnn --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement_rnn --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01
python MIMIC_discretized_exp.py --mode test --mgp_rnn_cls ManyToOneRNN --identifier 1023-15mins-24hrs-joint-indep-measurement-rnn --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement_rnn --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01

python MIMIC_discretized_exp.py --mode test --mgp_rnn_cls ManyToOneRNN --identifier 1023-15mins-24hrs-joint-indep-measurement-rnn-new --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement_rnn --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --database mingie_34features_6noise_new

python MIMIC_discretized_exp.py --mode val --mgp_rnn_cls ManyToOneRNN --identifier 1024-15mins-24hrs-joint-indep-measurement-rnn-all-pataient --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement_rnn --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --database mingie_34features_6noise --cache_all 1 --mgp_rnn_dir ../models/1022-12hours_34feats_6noise_negsampled-mimic-nh32-nl1-c1e-05-keeprate0.7_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingie_34features_6noise-ManyToOneRNN

python MIMIC_discretized_exp.py --mode test --mgp_rnn_cls ManyToOneRNN --identifier 1024-15mins-24hrs-joint-indep-measurement-rnn-all-pataient --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement_rnn --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --database mingie_34features_6noise --cache_all 1 --mgp_rnn_dir ../models/1022-12hours_34feats_6noise_negsampled-mimic-nh32-nl1-c1e-05-keeprate0.7_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingie_34features_6noise-ManyToOneRNN

# Cache all patient for the MGP-RNN
python MIMIC_discretized_exp.py --mode val --identifier 1030-15mins-24hrs-joint-indep-measurement-mgp-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 500 --database_name mingie_34features_6noise --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/0916-34feats_6noise_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.6_0.9-npred6-miss1-n_mc_15-MIMIC_window-mingie_34features_6noise-ManyToOneLMC_MGP_RNN/

# Cache with covariate!
./srun.sh -o ../logs/1102-mgp-rnn-cache-all-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1102-15mins-24hrs-joint-indep-measurement-mgp-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 500 --database_name mingie_34features --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

# Cache the patient for MGP-RNN w/o n_covs
./srun.sh -o ../logs/1102-mgp-rnn-no-cache-all-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1102-15mins-24hrs-joint-indep-measurement-mgp-rnn-all-pat-no-cov --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 500 --database_name mingie_34features --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled_nocov-mimic-nh32-nl1-c1e-05-keeprate0.7_0.7_0.5-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ --cache_proportion 0.05 &

# Cache with covariate in val set / train set
./srun.sh -o ../logs/1102-mgp-rnn-cache-all-pat-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1102-15mins-24hrs-joint-indep-measurement-mgp-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 500 --database_name mingie_34features --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

./srun.sh -o ../logs/1102-mgp-rnn-cache-all-pat-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1102-15mins-24hrs-joint-indep-measurement-mgp-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 500 --database_name mingie_34features --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

# Should do in sequential settings.....
./srun.sh -o ../logs/1103-mgp-rnn-cache-all-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1103-15mins-24hrs-random-order-mgp-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 30  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 2000 --database_name mingie_34features --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

./srun.sh -o ../logs/1103-mgp-rnn-cache-all-pat-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1103-15mins-24hrs-random-order-mgp-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 30  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

./srun.sh -o ../logs/1103-mgp-rnn-cache-all-pat-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1103-15mins-24hrs-random-order-mgp-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 30  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1200 --database_name mingie_34features --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &


./srun.sh -o ../logs/1103-mgp-rnn-cache-all-pat-testing.log python -u MIMIC_discretized_exp.py --mode testing --identifier 1103-15mins-24hrs-random-order-mgp-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 30  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1000 --database_name mingie_34features --cache_all 1 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

## Too many experience and patients to cache...
./srun.sh -o ../logs/1103-mgp-rnn-cache-pos-pat-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1103-15mins-24hrs-random-order-mgp-rnn-pos-only --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 30  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_all 0 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

./srun.sh -o ../logs/1103-mgp-rnn-cache-pos-pat-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1103-15mins-24hrs-random-order-mgp-rnn-pos-only --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 30  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_all 0 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

./srun.sh -o ../logs/1103-mgp-rnn-cache-pos-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1103-15mins-24hrs-random-order-mgp-rnn-pos-only --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 30  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_all 0 --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

# Do a negative subsampling of the dataset. And reduce num_random_orders to be at most 20
./srun.sh -o ../logs/1104-mgp-rnn-cache-neg_sampled-pat-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1104-15mins-24hrs-random-order-mgp-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 20  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_type neg_sampled --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

./srun.sh -o ../logs/1104-mgp-rnn-cache-neg_sampled-pat-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1104-15mins-24hrs-random-order-mgp-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 20  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_type neg_sampled --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &

./srun.sh -o ../logs/1104-mgp-rnn-cache-neg_sampled-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1104-15mins-24hrs-random-order-mgp-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 20  --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_type all --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1031-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_20-MIMIC_window-mingie_34features-ManyToOneLMC_MGP_RNN/ &


# Run a caching with RNN that caches with covs
./srun.sh -o ../logs/1104-rnn-cache-all-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1104-15mins-24hrs-joint-indep-measurement-rnn-all-pat --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --database_name mingie_34features --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1024-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_1-MIMIC_window-mingie_34features-ManyToOneRNN --cache_proportion 0.5 &

# So actually, the RNN looks OK in terms of dying patients / non-dying patients
./srun.sh -o ../logs/1104-rnn-cache-all-pat-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1104-15mins-24hrs-random-order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1024-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_1-MIMIC_window-mingie_34features-ManyToOneRNN --cache_proportion 1 &

./srun.sh -o ../logs/1104-rnn-cache-all-pat-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1104-15mins-24hrs-random-order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1024-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_1-MIMIC_window-mingie_34features-ManyToOneRNN --cache_proportion 1 &

./srun.sh -o ../logs/1104-rnn-cache-all-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1104-15mins-24hrs-random-order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingie_34features --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1024-12hours_34feats_negsampled-mimic-nh8-nl1-c1e-05-keeprate0.9_0.7_0.9-npred12-miss1-n_mc_1-MIMIC_window-mingie_34features-ManyToOneRNN --cache_proportion 1 &

# Do a RNN
./srun.sh -o ../logs/1115-rnn-cache-all-pat-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1117-15mins-24hrs-random-order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 &

./srun.sh -o ../logs/1115-rnn-cache-all-pat-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1117-15mins-24hrs-random-order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 &

./srun.sh -o ../logs/1115-rnn-cache-all-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1117-15mins-24hrs-random-order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 &

# Do a RNN individual bao to analyze.....
./srun.sh -o ../logs/1117-rnn-cache-neg_sampled-pat-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1117-15mins-24hrs-indep-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1. --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_independent_measurement &

# Run a MGP-RNN-cache
./srun.sh -o ../logs/1120-mgp-rnn-cache-all-pat-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1117-15mins-24hrs-random-order-mgp-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1117-12hours_39feats_38cov_negsampled_mgprnn_1-mimic-nh64-nl1-c1e-07-keeprate0.7_0.9_0.7-npred12-miss1-n_mc_20-MIMIC_window-mingjie_39features_38covs-ManyToOneLMC_MGP_RNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
./srun.sh -o ../logs/1120-mgp-rnn-cache-all-pat-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1117-15mins-24hrs-random-order-mgp-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1117-12hours_39feats_38cov_negsampled_mgprnn_1-mimic-nh64-nl1-c1e-07-keeprate0.7_0.9_0.7-npred12-miss1-n_mc_20-MIMIC_window-mingjie_39features_38covs-ManyToOneLMC_MGP_RNN --cache_proportion 1 &
./srun.sh -o ../logs/1120-mgp-rnn-cache-all-pat-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1117-15mins-24hrs-random-order-mgp-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1117-12hours_39feats_38cov_negsampled_mgprnn_1-mimic-nh64-nl1-c1e-07-keeprate0.7_0.9_0.7-npred12-miss1-n_mc_20-MIMIC_window-mingjie_39features_38covs-ManyToOneLMC_MGP_RNN --cache_proportion 1 &

# Run a MGP-RNN individual cache to analyze
./srun.sh -o ../logs/1120-mgp-rnn-cache-neg_sampled-pat-train-indep.log python -u MIMIC_discretized_exp.py --mode train --identifier 1117-15mins-24hrs-indep-mgp-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1117-12hours_39feats_38cov_negsampled_mgprnn_1-mimic-nh64-nl1-c1e-07-keeprate0.7_0.9_0.7-npred12-miss1-n_mc_20-MIMIC_window-mingjie_39features_38covs-ManyToOneLMC_MGP_RNN --cache_proportion 1. --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_independent_measurement &

# The test dead somehow. Run on my vws93 machine
python -u MIMIC_discretized_exp.py --mode test --identifier 1117-15mins-24hrs-random-order-mgp-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneLMC_MGP_RNN --mgp_rnn_dir ../models/1117-12hours_39feats_38cov_negsampled_mgprnn_1-mimic-nh64-nl1-c1e-07-keeprate0.7_0.9_0.7-npred12-miss1-n_mc_20-MIMIC_window-mingjie_39features_38covs-ManyToOneLMC_MGP_RNN --cache_proportion 1 &> ../logs/1120-mgp-rnn-cache-all-pat-test.log &


# Cache a policy with one pass random order (num_random_order = -1)
./srun.sh -o ../logs/1121-rnn-cache-neg-sampled-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1121-15mins-24hrs-one-random-order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order -1 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
./srun.sh -o ../logs/1121-rnn-cache-neg-sampled-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1121-15mins-24hrs-one-random-order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order -1 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &


# Cache RNN policy with 30 mins. After debuging
./srun.sh -o ../logs/1124-rnn-cache-neg-sampled-train.log python -u MIMIC_discretized_exp.py --mode train --identifier 1124-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
./srun.sh -o ../logs/1124-rnn-cache-neg-sampled-val.log python -u MIMIC_discretized_exp.py --mode val --identifier 1124-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
./srun.sh -o ../logs/1124-rnn-cache-neg-sampled-test.log python -u MIMIC_discretized_exp.py --mode test --identifier 1124-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &

# Cache per time :)
./srun.sh -o ../logs/1124-rnn-cache-neg-sampled-val_per_time.log python -u MIMIC_discretized_exp.py --mode val --identifier 1124-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_per_time_exp_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &

./srun.sh -o ../logs/1124-rnn-cache-neg-sampled-test_per_time.log python -u MIMIC_discretized_exp.py --mode test --identifier 1124-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_per_time_exp_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &

./srun.sh -o ../logs/1124-rnn-cache-neg-sampled-train_per_time.log python -u MIMIC_discretized_exp.py --mode train --identifier 1124-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_per_time_exp_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &

# Cache delaying update state
for cache_file in train val test
do
./srun.sh -o ../logs/0117-rnn-cache-neg-sampled-${cache_file}.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0117-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
done

# Cache delay update state with random order on per_time exp to plot tb :)
for cache_file in val test train
do
./srun.sh -o ../logs/0117-rnn-cache-neg-sampled-${cache_file}_per_time.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0117-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_per_time_exp_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
done


# Cache delay update state with all patients and one pass on test set
./srun.sh -o ../logs/1216-rnn-cache-all-test-one_pass.log python -u MIMIC_discretized_exp.py --mode test_onepass_all --identifier 0117-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order -1 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &

# 1228 cache a new env to directly regress the measuement
# (Use MIMIC_cache_exp_env_v3 to read it. The file is called 'test_per_time_env'
# TODO: maybe some bugs in the num_prev_time_actions?
for cache_file in val test train
do
./srun.sh -o ../logs/1228-rnn-cache-all-${cache_file}_per_time_env.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 1129-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_per_time_env_exp_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 12.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/1116-12hours_39feats_negsampled_38cov_rand-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred12-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_exp_env_v3 &
done

####### Do a new caching for 24 hours RNN ############
# Cache delaying update state
for cache_file in train val test
do
./srun.sh -o ../logs/0117-rnn-cache-neg-sampled-${cache_file}.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0117-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
done

# Cache delay update state with random order on per_time exp to plot tb :)
#for cache_file in val test train
#do
#./srun.sh -o ../logs/0117-rnn-cache-neg-sampled-${cache_file}_per_time.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0117-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_per_time_exp_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
#done


# Cache delay update state with all patients and one pass on test set
./srun.sh -o ../logs/0117-rnn-cache-all-test-one_pass.log python -u MIMIC_discretized_exp.py --mode test_onepass_all --identifier 0117-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order -1 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &

# (Use MIMIC_cache_exp_env_v3 to read it. The file is called 'test_per_time_env'
for cache_file in val test train
do
./srun.sh -o ../logs/0117-rnn-cache-all-${cache_file}_per_time_env.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0117-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_per_time_env_exp_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_exp_env_v3 &
done

# Fix random_order cls that I forget to cache the cur_prob and next_prob
# Cache delaying update state
for cache_file in train val test
do
./srun.sh -o ../logs/0118-rnn-cache-neg-sampled-${cache_file}.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0118-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &
done

# Cache delay update state with all patients and one pass on test set
./srun.sh -o ../logs/0118-rnn-cache-all-test-one_pass.log python -u MIMIC_discretized_exp.py --mode test_onepass_all --identifier 0118-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_rnn --num_random_order -1 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order &


## Recache the per_time for train & val since using neg_sampled accidentally
for cache_file in val train
do
./srun.sh -o ../logs/0121-rnn-cache-all-${cache_file}_per_time_env.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0121-30mins-24hrs-20order-rnn-neg_sampled --MIMIC_exp_cls MIMIC_per_time_env_exp_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_exp_env_v3 &
done

## Rebutal: use the individual part to do K tails?
for mode in train val test
do
./srun.sh -o ../logs/0311-rnn-cache-neg_sampled-pat-${mode}.log python -u MIMIC_discretized_exp.py --mode ${mode} --identifier 0311-30mins-24hrs-indep-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement_rnn --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1. --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_independent_measurement &
done

mode=train
./srun.sh -o ../logs/0311-rnn-cache-neg_sampled-pat-${mode}-2.log python -u MIMIC_discretized_exp.py --mode ${mode} --identifier 0311-30mins-24hrs-indep-rnn-neg_sampled --MIMIC_exp_cls MIMIC_discretized_joint_exp_independent_measurement_rnn --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1. --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_independent_measurement &

## Rebuttal: use the last observation as the state
for cache_file in train val test
do
./srun.sh -o ../logs/0312-rnn-cache-neg-sampled-${cache_file}.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0312-30mins-24hrs-20order-rnn-neg_sampled-with-obs --MIMIC_exp_cls MIMIC_discretized_joint_exp_random_order_with_obs_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type neg_sampled --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_joint_exp_random_order_with_obs &
done

for cache_file in train val test
do
./srun.sh -o ../logs/0312-rnn-cache-env-${cache_file}.log python -u MIMIC_discretized_exp.py --mode ${cache_file} --identifier 0312-30mins-24hrs-20order-rnn-neg_sampled-with-obs --MIMIC_exp_cls MIMIC_per_time_env_exp_last_obs_rnn --num_random_order 20 --include_before_death 24 --min_hours_of_patient 12 --num_hours_pred 24.01 --batch_size 1600 --database_name mingjie_39features_38covs --cache_type all --mgp_rnn_cls ManyToOneRNN --mgp_rnn_dir ../models/0117-24hours_39feats_38cov_negsampled_rnn-mimic-nh128-nl2-c1e-07-keeprate0.9_0.7_0.5-npred24-miss1-n_mc_1-MIMIC_window-mingjie_39features_38covs-ManyToOneRNN/ --cache_proportion 1 --MIMIC_cache_exp_cls MIMIC_cache_discretized_exp_env_v3_last_obs &
done



